### ISSUE TITLE
Strange Output for Linting Add-on

### ISSUE THREAD

**Issue by FrancescoSTL** [mozilla/addons-linter#930]
Andym ran my add-on (https://github.com/FrancescoSTL/Site-Sonar) and received the following output from the linter: 

```
master Site-Sonar $ ~/sandboxes/addons-linter/bin/addons-linter --stack .
TypeError: Cannot read property 'init' of undefined
    at /Users/andy/sandboxes/addons-linter/dist/webpack:/src/utils.js:125:16
    at Array.forEach (native)
    at getVariable (/Users/andy/sandboxes/addons-linter/dist/webpack:/src/utils.js:123:13)
    at EventEmitter.CallExpression (/Users/andy/sandboxes/addons-linter/dist/webpack:/src/rules/javascript/eval_string_arg.js:16:29)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (/Users/andy/sandboxes/addons-linter/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/andy/sandboxes/addons-linter/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/Users/andy/sandboxes/addons-linter/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/Users/andy/sandboxes/addons-linter/node_modules/eslint/lib/eslint.js:895:36)
```

https://dpaste.de/VxJP#L

It is causing a "general test" failure on AMO when attempting to update the add-on.

**Comment by FrancescoSTL** [comment]
I've located the problem commit in my own repo by checking the linter against all previous versions until I got the above error: https://github.com/FrancescoSTL/Site-Sonar/commit/0f7766de480e5da150ccbaf918c6b9b191dbc0e9

**Comment by FrancescoSTL** [comment]
The first error I was getting (in the original post) was fixed by exchanging `window.setInterval(x)` with just `setInterval(x)` in https://github.com/FrancescoSTL/Site-Sonar/blob/0f7766de480e5da150ccbaf918c6b9b191dbc0e9/js/userReport.js#L12

Now I'm getting a new ambiguous error (hooray!):
```
SyntaxError: Unexpected token /
    at Object.parse (native)
    at new SourceMapConsumer (/usr/local/lib/node_modules/addons-linter/node_modules/postcss/node_modules/source-map/lib/source-map-consumer.js:17:22)
    at PreviousMap.consumer (/source/previous-map.es6:46:34)
    at new Input (/source/input.es6:69:28)
    at Object.parse (/source/parse.es6:10:17)
    at /usr/local/lib/node_modules/addons-linter/dist/webpack:/src/scanners/css.js:78:35
    at new Promise (/usr/local/lib/node_modules/addons-linter/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:191:7)
    at CSSScanner._getContents (/usr/local/lib/node_modules/addons-linter/dist/webpack:/src/scanners/css.js:76:12)
    at /usr/local/lib/node_modules/addons-linter/dist/webpack:/src/scanners/base.js:70:12
    at new Promise (/usr/local/lib/node_modules/addons-linter/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:191:7)
```

**Comment by FrancescoSTL** [comment]
Looks like I wasn't getting the same error above in my master branch. It was localized to my bootstrap.min.css file. All fixed after https://github.com/mozilla/addons-linter/issues/930#issuecomment-245435200

**Comment by andymckay** [comment]
Glad its working for you. But wouldn't mind keeping this open so we can fix this for other users.

**Comment by wagnerand** [comment]
I just ran https://github.com/FrancescoSTL/Site-Sonar/tree/0f7766de480e5da150ccbaf918c6b9b191dbc0e9 against the linter (0.22.7), and I am still getting the same stacktrace:

```
$ addons-linter --stack  web-ext-artifacts/site-sonar-1.0.zip
SyntaxError: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at new SourceMapConsumer (/usr/local/lib/node_modules/addons-linter/node_modules/source-map/lib/source-map-consumer.js:17:22)
    at PreviousMap.consumer (/usr/local/lib/node_modules/addons-linter/node_modules/postcss/lib/previous-map.es6:57:34)
    at new Input (/usr/local/lib/node_modules/addons-linter/node_modules/postcss/lib/input.es6:62:28)
    at Object.parse (/usr/local/lib/node_modules/addons-linter/node_modules/postcss/lib/parse.es6:10:17)
    at /usr/local/lib/node_modules/addons-linter/dist/webpack:/src/scanners/css.js:85:35
    at Promise (<anonymous>)
    at CSSScanner._getContents (/usr/local/lib/node_modules/addons-linter/dist/webpack:/src/scanners/css.js:83:12)
    at /usr/local/lib/node_modules/addons-linter/dist/webpack:/src/scanners/base.js:85:12
    at Promise (<anonymous>)
(node:48394) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): SyntaxError: Unexpected token / in JSON at position 0
(node:48394) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by EnTeQuAk** [comment]
I ran the most recent version of the linter against that add-on and can't reproduce this error anymore.

Closing.
